package foriba.com.jws2product;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "JWS2ProductPortType", targetNamespace = "http://com.foriba/JWS2Product")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface JWS2ProductPortType {

  /**
   * Java representation of web method [getProductList].
 * @throws Exception 
   */
  @javax.jws.WebMethod(operationName = "getProductList", action = "getProductList")
  @javax.jws.WebResult(name = "getProductListResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.GetProductListResponse getProductList(@javax.jws.WebParam(name = "getProductListRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.GetProductListRequest parameter) throws Exception;

  /**
   * Java representation of web method [addProduct].
 * @throws Exception 
   */
  @javax.jws.WebMethod(operationName = "addProduct", action = "addProduct")
  @javax.jws.WebResult(name = "addProductResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.AddProductResponse addProduct(@javax.jws.WebParam(name = "addProductRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.AddProductRequest parameter) throws Exception;

  /**
   * Java representation of web method [updateProductName].
   */
  @javax.jws.WebMethod(operationName = "updateProductName", action = "updateProductName")
  @javax.jws.WebResult(name = "updateProductNameResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.UpdateProductNameResponse updateProductName(@javax.jws.WebParam(name = "updateProductNameRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.UpdateProductNameRequest parameter);

  /**
   * Java representation of web method [getProductByProdName].
   */
  @javax.jws.WebMethod(operationName = "getProductByProdName", action = "getProductByProdName")
  @javax.jws.WebResult(name = "getProductByProdNameResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.GetProductByProdNameResponse getProductByProdName(@javax.jws.WebParam(name = "getProductByProdNameRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.GetProductByProdNameRequest parameter);

  /**
   * Java representation of web method [getProductListByMultipleProdDate].
 * @throws Exception 
   */
  @javax.jws.WebMethod(operationName = "getProductListByMultipleProdDate", action = "getProductListByMultipleProdDate")
  @javax.jws.WebResult(name = "getProductListByMultipleProdDateResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.GetProductListByMultipleProdDateResponse getProductListByMultipleProdDate(@javax.jws.WebParam(name = "getProductListByMultipleProdDateRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.GetProductListByMultipleProdDateRequest parameter) throws Exception;

  /**
   * Java representation of web method [getProductListByProdDate].
   */
  @javax.jws.WebMethod(operationName = "getProductListByProdDate", action = "getProductListByProdDate")
  @javax.jws.WebResult(name = "getProductListByProdDateResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.GetProductListByProdDateResponse getProductListByProdDate(@javax.jws.WebParam(name = "getProductListByProdDateRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.GetProductListByProdDateRequest parameter);

  /**
   * Java representation of web method [getProductListByProdName].
   */
  @javax.jws.WebMethod(operationName = "getProductListByProdName", action = "getProductListByProdName")
  @javax.jws.WebResult(name = "getProductListByProdNameResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.GetProductListByProdNameResponse getProductListByProdName(@javax.jws.WebParam(name = "getProductListByProdNameRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.GetProductListByProdNameRequest parameter);

  /**
   * Java representation of web method [removeProduct].
   */
  @javax.jws.WebMethod(operationName = "removeProduct", action = "removeProduct")
  @javax.jws.WebResult(name = "removeProductResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.RemoveProductResponse removeProduct(@javax.jws.WebParam(name = "removeProductRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.RemoveProductRequest parameter);

  /**
   * Java representation of web method [getProductByID].
   */
  @javax.jws.WebMethod(operationName = "getProductByID", action = "getProductByID")
  @javax.jws.WebResult(name = "getProductByIDResponse", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter")
  public foriba.com.jws2product.GetProductByIDResponse getProductByID(@javax.jws.WebParam(name = "getProductByIDRequest", targetNamespace = "http://com.foriba/JWS2Product", partName = "parameter") foriba.com.jws2product.GetProductByIDRequest parameter);

}
